/*
  研究項目資料：研究頁簡介、組織架構、研究分類與研究文章。
  新增或修改研究項目時，主要改這裡。
*/
window.TMRC_RESEARCH_DATA = {
  "researchIntro": {
    "zhTW": "本中心設有三個研究技術組，分別為元件及系統設計組、熱傳裝置製造組與熱傳材料技術組三大面向推動研究進行：",
    "en": "The Center promotes research through three specialized technical groups: the Component and System Design Group, the Heat Transfer Device Manufacturing Group, and the Heat Transfer Material Technology Group:"
  },
  "orgChart": {
    "zhTW": {
      "director": "主任",
      "committee": "執行委員會",
      "groups": [
        {
          "title": "元件及系統設計組",
          "convener": "楊建裕",
          "members": "楊建裕、吳俊諆、陳冠廷"
        },
        {
          "title": "熱傳裝置製造組",
          "convener": "何正榮",
          "members": "何正榮、曹嘉文"
        },
        {
          "title": "熱傳材料技術組",
          "convener": "劉正毓",
          "members": "林景崎、劉正毓"
        }
      ],
      "convenerLabel": "召集人：",
      "membersLabel": "成員："
    },
    "en": {
      "director": "Director",
      "committee": "Executive Committee",
      "groups": [
        {
          "title": "Component and System Design",
          "convener": "Yang, Chien-Yuh",
          "members": "Yang, Chien-Yuh; Wu, Jiunn-Chi; Chen, Kuan-Ting"
        },
        {
          "title": "Heat Transfer Device Manufacturing",
          "convener": "Ho, Jeng-Rong",
          "members": "Ho, Jeng-Rong; Tsao, Chia-Wen"
        },
        {
          "title": "Heat Transfer Material Technology",
          "convener": "Liu, Cheng-Yi",
          "members": "Lin, Jing-Chie; Liu, Cheng-Yi"
        }
      ],
      "convenerLabel": "Convener: ",
      "membersLabel": "Members: "
    }
  },
  "researchCategories": [
    {
      "id": "component-system-design",
      "items": [
        "vapor-chamber-cold-plate-fin-design",
        "thermal-mechanism-simulation",
        "heat-exchanger-design"
      ],
      "zhTW": {
        "title": "一、元件及系統設計組",
        "description": "本組透過熱模擬與熱流分析技術，依照高功率晶片的實際需求設計最合適的散熱模組，滿足未來高速運算與AI晶片的熱管理挑戰。"
      },
      "en": {
        "title": "I. Component and System Design Group",
        "description": "This group utilizes thermal simulation and fluid flow analysis to design optimized cooling modules tailored to high-power chips, addressing the heat management challenges of next-generation HPC and AI hardware."
      }
    },
    {
      "id": "device-manufacturing",
      "items": [
        "five-axis-milling",
        "ultrafast-laser-processing",
        "microchannel-manufacturing-platform"
      ],
      "zhTW": {
        "title": "二、熱傳裝置製造組",
        "description": "本組藉由結合AI熱模擬與先進機台，打破傳統製程限制，開發適用於新世代高密度封裝的高性能散熱裝置。"
      },
      "en": {
        "title": "II. Heat Transfer Device Manufacturing Group",
        "description": "By combining AI-driven thermal simulation with advanced machinery, this group overcomes traditional manufacturing constraints to develop high-performance cooling devices for next-generation high-density packaging."
      }
    },
    {
      "id": "thermal-materials",
      "items": [
        "liquid-metal-tim",
        "material-corrosion-improvement",
        "filler-design-tim"
      ],
      "zhTW": {
        "title": "三、熱傳材料技術組",
        "description": "本組以材料創新為核心，開發符合未來高功率晶片應用的熱傳界面與結構材料，有效提升系統散熱效率與可靠性。"
      },
      "en": {
        "title": "III. Heat Transfer Material Technology Group",
        "description": "Focused on material innovation, this group develops thermal interface and structural materials for high-power chip applications, effectively enhancing system cooling efficiency and reliability."
      }
    }
  ],
  "researchArticles": [
    {
      "id": "vapor-chamber-cold-plate-fin-design",
      "categoryId": "component-system-design",
      "zhTW": {
        "title": "均溫板、冷板與散熱鰭片設計",
        "sections": [
          {
            "heading": "研究內容",
            "paragraphs": [
              "本項研究主要依據晶片各晶核（Die）所產生之熱量以及熱傳路徑進行設計。基本電子晶片散熱機構中，晶核所產生之熱會先經由均溫板（Spreader）擴散，再傳至散熱鰭片（Fin）或冷板（Cold plate），最後傳至大氣；而在晶核與均溫板之間、以及均溫板與冷板或鰭片之間，需填充熱介面材料（TIM）以降低接觸熱阻。設計的基礎在於先透過模擬分析了解各晶核的詳細溫度分布，並據以設計所需之熱交換器，涵蓋均溫板、冷板以及鰭片等不同類型的熱交換器設計。"
            ],
            "images": [
              {
                "src": "images/Basic Chip Cooling Structure.png",
                "alt": "基本晶片散熱機構",
                "caption": "基本晶片散熱機構"
              }
            ]
          }
        ]
      },
      "en": {
        "title": "Design of Vapor Chambers, Cold Plates, and Heat Sink Fins",
        "sections": [
          {
            "heading": "Research Content",
            "paragraphs": [
              "This research focuses on designing cooling solutions based on the heat generation and heat transfer paths of individual dies within a chip. In a basic electronic chip cooling mechanism, the heat generated by the die is first spread through a vapor chamber (spreader), then transferred to heat sink fins or a cold plate, and finally dissipated into the atmosphere. Thermal Interface Materials (TIMs) must be applied between the die and the vapor chamber, as well as between the vapor chamber and the cold plate or fins, to reduce contact thermal resistance. The foundation of this design lies in understanding the detailed temperature distribution of each die through simulation analysis, and subsequently designing the required heat exchangers, encompassing various types such as vapor chambers, cold plates, and fins."
            ],
            "images": [
              {
                "src": "images/Basic Chip Cooling Structure.png",
                "alt": "Basic Chip Cooling Structure",
                "caption": "Basic Chip Cooling Structure"
              }
            ]
          }
        ]
      }
    },
    {
      "id": "thermal-mechanism-simulation",
      "categoryId": "component-system-design",
      "zhTW": {
        "title": "晶片元件熱傳機制分析與溫度分布模擬",
        "sections": [
          {
            "heading": "研究內容",
            "paragraphs": [
              "此項工作是散熱設計的前端核心，重點在於針對晶片各元件的熱傳機制及溫度分布進行模擬分析。透過精確的晶核溫度分布模擬分析，能夠詳細了解各晶核在運作時的溫度分布情形；這些數據將直接作為後續熱交換器設計的重要依據，確保設計能精準對應熱源，並依照實際需求規劃合適的熱交換器與散熱模組。"
            ],
            "images": [
              {
                "src": "images/Chip Power Trend.png",
                "alt": "歷年IC晶片發熱量成長演變",
                "caption": "歷年IC晶片發熱量成長演變"
              }
            ]
          }
        ]
      },
      "en": {
        "title": "Analysis of Heat Transfer Mechanisms and Temperature Distribution Simulation for Chip Components",
        "sections": [
          {
            "heading": "Research Content",
            "paragraphs": [
              "This task is the front-end core of thermal design, focusing on simulating and analyzing the heat transfer mechanisms and temperature distribution of various chip components. Through precise simulation analysis of die temperature distribution, we can understand in detail the temperature profile of each die during operation. These data will directly serve as a crucial basis for subsequent heat exchanger design, ensuring that the design accurately targets the heat sources and formulates appropriate heat exchangers and cooling modules according to actual requirements."
            ],
            "images": [
              {
                "src": "images/Chip Power Trend.png",
                "alt": "Trend of IC Chip Heat Generation over the Years",
                "caption": "Trend of IC Chip Heat Generation over the Years"
              }
            ]
          }
        ]
      }
    },
    {
      "id": "heat-exchanger-design",
      "categoryId": "component-system-design",
      "zhTW": {
        "title": "單相與兩相熱交換器設計",
        "sections": [
          {
            "heading": "研究內容",
            "paragraphs": [
              "熱交換器之目的在於將各晶核所產生之熱傳遞至大氣，依據熱傳機制可分為直接氣體冷卻或液體冷卻。直接氣體冷卻所需熱交換器為散熱鰭片，主要用在低功率、低發熱量之晶片散熱；而液體冷卻則使用冷板將晶片所產生之熱，經由單相液體或兩相蒸發方式傳至伺服器外部，再藉由外部較大型之散熱器散逸至大氣，適用於中、高功率及發熱量之晶片散熱。近年來由於運算速度快速成長，發熱量急遽增加，業界已開始使用單相液體冷卻方式，例如 nVIDIA 從 2023 年發表之 H200 晶片開始，即指定液體冷卻為標準散熱規格，且預期未來晶片之發熱量持續增加，兩相蒸發冷卻將成為必要之選項。"
            ],
            "images": [
              {
                "src": "images/Cooling Market Growth.png",
                "alt": "全球資料中心冷卻市場 (Grand View Research, Market analysis report, 2024)",
                "caption": "全球資料中心冷卻市場 (Grand View Research, Market analysis report, 2024)"
              }
            ]
          }
        ]
      },
      "en": {
        "title": "Design of Single-Phase and Two-Phase Heat Exchangers",
        "sections": [
          {
            "heading": "Research Content",
            "paragraphs": [
              "The purpose of a heat exchanger is to transfer the heat generated by each die to the atmosphere. Based on the heat transfer mechanism, it can be divided into direct air cooling or liquid cooling. The heat exchanger required for direct air cooling is a heat sink fin, mainly used for cooling low-power, low-heat chips. Liquid cooling, on the other hand, uses cold plates to transfer the heat generated by the chip to the outside of the server via single-phase liquid or two-phase evaporation, and then dissipates it to the atmosphere through a larger external radiator. This is suitable for medium and high-power chip cooling. In recent years, due to the rapid growth of computing speed and a sharp increase in heat generation, the industry has begun to adopt single-phase liquid cooling. For instance, nVIDIA specified liquid cooling as the standard thermal specification starting from the H200 chip released in 2023. It is expected that as chip heat generation continues to increase, two-phase evaporative cooling will become an essential option."
            ],
            "images": [
              {
                "src": "images/Cooling Market Growth.png",
                "alt": "Global Data Center Cooling Market",
                "caption": "Global Data Center Cooling Market (Grand View Research, Market analysis report, 2024)"
              }
            ]
          }
        ]
      }
    },
    {
      "id": "five-axis-milling",
      "categoryId": "device-manufacturing",
      "zhTW": {
        "title": "五軸銑削製程，金屬微結構加工",
        "sections": [
          {
            "heading": "研究內容",
            "paragraphs": [
              "本項研究旨在開發五軸銑削等精密製程技術，並應用於高性能熱交換器的製造。雖然傳統銑削技術已可加工出多樣的金屬微結構並廣泛應用於產業界，但隨著高功率與微型化晶片技術的快速發展，傳統銑削在刀具尺寸與加工能力方面的限制，已難以滿足未來高效能熱管理系統對微結構精度與複雜度的設計需求。此外，目前多數製程仍以二維堆疊方式進行微結構製作，導致在結構形狀、尺寸、密度與佈局設計上受限；相比之下，三維微流道結構不僅能顯著提升熱交換表面積，更能有效利用三維空間進行熱傳優化設計，提升散熱效率，因此本中心導入具備高度靈活性與精度的五軸加工技術，開發三維金屬微結構製程，以突破傳統製程侷限，發展適用於次世代高效熱傳裝置。"
            ],
            "images": [
              {
                "src": "images/CNC Microfabrication Flow.png",
                "alt": "五軸加工中心加工示意圖",
                "caption": "五軸加工中心加工示意圖"
              }
            ]
          }
        ]
      },
      "en": {
        "title": "Five-Axis Milling Processes and Metal Microstructure Machining",
        "sections": [
          {
            "heading": "Research Content",
            "paragraphs": [
              "This research aims to develop precision manufacturing technologies such as five-axis milling and apply them to the manufacturing of high-performance heat exchangers. Although traditional milling technology can process various metal microstructures and is widely used in the industry, with the rapid development of high-power and miniaturized chip technologies, the limitations of traditional milling in tool size and processing capability can hardly meet the design requirements for the precision and complexity of microstructures in future high-efficiency thermal management systems. Moreover, most current processes still produce microstructures using a two-dimensional stacking method, resulting in limitations in structural shape, size, density, and layout design. In contrast, three-dimensional microchannel structures can not only significantly increase the heat exchange surface area but also effectively utilize 3D space for thermal transfer optimization design, improving cooling efficiency. Therefore, our center has introduced a five-axis machining center with high flexibility and precision to develop 3D metal microstructure processes, breaking through the limitations of traditional processes to develop next-generation high-efficiency heat transfer devices."
            ],
            "images": [
              {
                "src": "images/CNC Microfabrication Flow.png",
                "alt": "Schematic of Five-Axis Machining Center Process",
                "caption": "Schematic of Five-Axis Machining Center Process"
              }
            ]
          }
        ]
      }
    },
    {
      "id": "ultrafast-laser-processing",
      "categoryId": "device-manufacturing",
      "zhTW": {
        "title": "超快雷射加工（皮秒/飛秒），無接觸微加工技術",
        "sections": [
          {
            "heading": "研究內容",
            "paragraphs": [
              "本項目開發超快雷射加工等高精度非接觸式製程技術，應用於次世代電子與半導體高效能散熱模組之製造。隨著高功率、高整合度晶片技術（如 CoWoS、3D IC、玻璃中介層等）快速演進，傳統接觸式加工技術面臨微結構尺寸受限、材料損耗與加工熱影響區過大等挑戰，已難以滿足新世代封裝散熱模組對複雜微結構、高密度三維流道與異質材料加工的需求。超快雷射具備極短脈衝時間與高峰值能量，能在極小熱影響區條件下，實現對金屬、玻璃、陶瓷等材料的高精度微細加工。"
            ],
            "images": [
              {
                "src": "images/Ultrafast Laser Setup.png",
                "alt": "超快雷射加工系統示意圖",
                "caption": "開發雷射新穎製程技術，在創新基板材料中建立高效能散熱與導熱微結構"
              }
            ]
          }
        ]
      },
      "en": {
        "title": "Ultrafast Laser Processing (Picosecond/Femtosecond) and Non-Contact Micromachining Technology",
        "sections": [
          {
            "heading": "Research Content",
            "paragraphs": [
              "This project develops high-precision non-contact manufacturing technologies, such as ultrafast laser processing, applied to the manufacturing of next-generation high-performance cooling modules for electronics and semiconductors. As high-power, high-integration chip technologies (e.g., CoWoS, 3D IC, glass interposers) rapidly evolve, traditional contact processing technologies face challenges such as limited microstructure sizes, material wear, and excessively large heat-affected zones (HAZ). These traditional methods struggle to meet the demands of next-generation packaging cooling modules for complex microstructures, high-density 3D flow channels, and heterogeneous material processing. Ultrafast lasers possess extremely short pulse durations and high peak energy, enabling high-precision micromachining of materials like metals, glass, and ceramics with minimal heat-affected zones."
            ],
            "images": [
              {
                "src": "images/Ultrafast Laser Setup.png",
                "alt": "Ultrafast Laser Processing Setup",
                "caption": "Development of novel laser manufacturing technologies to create high-efficiency heat dissipation and thermal conduction microstructures in innovative substrate materials"
              }
            ]
          }
        ]
      }
    },
    {
      "id": "microchannel-manufacturing-platform",
      "categoryId": "device-manufacturing",
      "zhTW": {
        "title": "微流道與高密度散熱結構製程平台",
        "sections": [
          {
            "heading": "研究內容",
            "paragraphs": [
              "透過雷射直接寫入（Direct Writing）、選區燒蝕或掃描式雷射誘導蝕刻等機制，本項目可在玻璃中介層、瓷金基板等材料上建立微米級高密度三維流道結構，顯著提升散熱效率，並為未來高密度封裝模組提供新穎的熱管理解決方案。本研究導入高功率皮秒/飛秒雷射加工系統，結合 AI 數位熱模擬與雷射路徑優化演算法，發展適用於高複雜度微流道設計之製程平台，以突破傳統加工極限，實現功能整合、高效率與高可靠性的先進封裝散熱模組。"
            ],
            "images": [
              {
                "src": "images/Ultrafast Laser Setup.png",
                "alt": "雷射新穎製程技術示意圖",
                "caption": "開發雷射新穎製程技術，在創新基板材料中建立高效能散熱與導熱微結構"
              }
            ]
          }
        ]
      },
      "en": {
        "title": "Manufacturing Platforms for Microchannels and High-Density Heat Dissipation Structures",
        "sections": [
          {
            "heading": "Research Content",
            "paragraphs": [
              "Through mechanisms such as laser direct writing, selective ablation, or scanning laser-induced etching, this project can establish micrometer-scale, high-density 3D flow channel structures on materials like glass interposers and cermet substrates. This significantly enhances cooling efficiency and provides novel thermal management solutions for future high-density packaging modules. This research introduces a high-power picosecond/femtosecond laser processing system, combined with AI digital thermal simulation and laser path optimization algorithms, to develop a manufacturing platform suitable for highly complex microchannel designs. The goal is to break through traditional processing limits and realize advanced packaging cooling modules with functional integration, high efficiency, and high reliability."
            ],
            "images": [
              {
                "src": "images/Ultrafast Laser Setup.png",
                "alt": "Novel Laser Manufacturing Technology",
                "caption": "Development of novel laser manufacturing technologies to create high-efficiency heat dissipation and thermal conduction microstructures in innovative substrate materials"
              }
            ]
          }
        ]
      }
    },
    {
      "id": "liquid-metal-tim",
      "categoryId": "thermal-materials",
      "zhTW": {
        "title": "液態金屬（如鎵銦錫合金）熱界面材料開發與改質",
        "sections": [
          {
            "heading": "研究內容",
            "paragraphs": [
              "熱界面材料之主要功能在於填充各熱傳元件間之間隙，降低接觸熱阻。由於一般介面材料厚度薄、相對於其他熱傳元件熱阻值低，因此在晶片發熱量不高時，其熱傳導性對整體熱傳性能影響不大，多使用混和金屬粉末之矽膠為之；然而近年來熱交換器從直接氣冷進入液體冷卻後，熱阻降為直接氣冷鰭片之百分之一以下，因此熱介面材料的熱傳導性變得非常重要。本研究使用鎵、銦和錫三元合金為基底（matrix）之液態金屬（liquid metal, LM），其同時兼具流動性、高導熱性、高體積相變潛熱等特性，且其熱傳係數遠高於現有 silicon-based 熱介面材料，為先進散熱技術帶來顛覆性變革。"
            ],
            "images": [
              {
                "src": "images/High-Conductivity LM TIM Process.png",
                "alt": "研發含不同填料之高熱導LM TIM及製程建立",
                "caption": "研發含不同填料之高熱導 LM TIM 及製程建立"
              }
            ]
          }
        ]
      },
      "en": {
        "title": "Development and Modification of Liquid Metal (e.g., Galinstan) Thermal Interface Materials",
        "sections": [
          {
            "heading": "Research Content",
            "paragraphs": [
              "The main function of Thermal Interface Materials (TIMs) is to fill the gaps between various heat transfer components, reducing contact thermal resistance. Since typical interface materials are thin and have lower thermal resistance compared to other heat transfer components, their thermal conductivity does not significantly impact overall heat transfer performance when chip heat generation is low; thus, silicone mixed with metal powders is often used. However, as heat exchangers transition from direct air cooling to liquid cooling in recent years, thermal resistance drops to less than 1% of direct air-cooled fins. Consequently, the thermal conductivity of TIMs has become crucial. This research utilizes liquid metal (LM) based on a ternary alloy of gallium, indium, and tin (Galinstan) as a matrix. It combines fluidity, high thermal conductivity, and high volumetric latent heat of phase change. Its heat transfer coefficient is far superior to existing silicone-based TIMs, bringing disruptive changes to advanced cooling technologies."
            ],
            "images": [
              {
                "src": "images/High-Conductivity LM TIM Process.png",
                "alt": "Development of High-Conductivity LM TIM",
                "caption": "Development of highly thermally conductive LM TIMs with various fillers and establishment of manufacturing processes"
              }
            ]
          }
        ]
      }
    },
    {
      "id": "material-corrosion-improvement",
      "categoryId": "thermal-materials",
      "zhTW": {
        "title": "熱交換器材料（銅、鋁）之腐蝕與耐候性改善",
        "sections": [
          {
            "heading": "研究內容",
            "paragraphs": [
              "本項目針對熱交換器耐蝕及耐候材料進行研究。由於紅銅具備高熱傳導性，目前一般多採用其為熱交換器材料；但由於銅的重量及價格皆遠高於鋁，因此業界開始考慮在移動裝置（如電動車）之電子設備熱管理使用鋁質熱交換器。然而鋁耐候性較差，且與銅有電位腐蝕問題，因此本組將針對相關材料腐蝕抑制問題進行開發及改善，以提升材料在實際應用下的可靠度與耐久性 。"
            ],
            "images": []
          }
        ]
      },
      "en": {
        "title": "Improvement of Corrosion and Weather Resistance for Heat Exchanger Materials (Copper, Aluminum)",
        "sections": [
          {
            "heading": "Research Content",
            "paragraphs": [
              "This project researches corrosion-resistant and weather-resistant materials for heat exchangers. Due to its high thermal conductivity, copper (red copper) is currently widely used as a heat exchanger material. However, because the weight and price of copper are much higher than aluminum, the industry has started to consider using aluminum heat exchangers for thermal management of electronic equipment in mobile devices (such as electric vehicles). Nevertheless, aluminum has poorer weather resistance and faces galvanic corrosion issues when in contact with copper. Therefore, this group focuses on the development and improvement of corrosion inhibition for related materials to enhance their reliability and durability in practical applications."
            ],
            "images": []
          }
        ]
      }
    },
    {
      "id": "filler-design-tim",
      "categoryId": "thermal-materials",
      "zhTW": {
        "title": "填料設計與流變性調控，製作高κ值TIMs",
        "sections": [
          {
            "heading": "研究內容",
            "paragraphs": [
              "本研究透過在液態金屬基底中添加金屬、非金屬的填料（filler）以提升 LM TIMs 的熱傳導係數，並藉由調變液態金屬之流變性質，增廣其應用領域之研發及應用。由於兼具各種綜合優勢，液態金屬有望成為理想的超高功率密度散熱材料；本項目的最終目標是製作出符合次世代需求的高 κ 值 LM TIMs，帶動構建嶄新的技術應用體系。"
            ],
            "images": [
              {
                "src": "images/High-Conductivity LM TIM Process.png",
                "alt": "研發含不同填料之高熱導LM TIM及製程建立",
                "caption": "研發含不同填料之高熱導 LM TIM 及製程建立"
              }
            ]
          }
        ]
      },
      "en": {
        "title": "Filler Design and Rheology Control to Produce High-κ Thermal Interface Materials (TIMs)",
        "sections": [
          {
            "heading": "Research Content",
            "paragraphs": [
              "This research aims to enhance the thermal conductivity of LM TIMs by adding metallic and non-metallic fillers into the liquid metal matrix. By modulating the rheological properties of liquid metal, we expand its research and application scope. Combining various comprehensive advantages, liquid metal is expected to become an ideal ultra-high power density heat dissipation material. The ultimate goal of this project is to produce high-κ LM TIMs that meet next-generation requirements, driving the construction of a brand-new technological application system."
            ],
            "images": [
              {
                "src": "images/High-Conductivity LM TIM Process.png",
                "alt": "Development of High-Conductivity LM TIM",
                "caption": "Development of highly thermally conductive LM TIMs with various fillers and establishment of manufacturing processes"
              }
            ]
          }
        ]
      }
    }
  ]
};
